# Generated by Django 5.2.9 on 2025-12-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproducts',
            name='embedding_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
