# Generated by Django 5.2.9 on 2025-12-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_depositproducts_embedding_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('join_way', models.TextField()),
                ('etc_note', models.TextField()),
                ('join_deny', models.IntegerField(blank=True, null=True)),
                ('join_member', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('dcls_month', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
