# Generated by Django 5.2.9 on 2025-12-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0003_savingproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='financial_products',
        ),
        migrations.AddField(
            model_name='user',
            name='joined_deposits',
            field=models.ManyToManyField(blank=True, related_name='joined_users', to='products.depositproducts'),
        ),
        migrations.AddField(
            model_name='user',
            name='joined_savings',
            field=models.ManyToManyField(blank=True, related_name='joined_users', to='products.savingproducts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
